/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.arch;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class IngeniousDigitsTest {
    @Test void useCase1() {
        String zeros =
            " _  _  _  _  _  _  _  _  _ \n" +
            "| || || || || || || || || |\n" +
            "|_||_||_||_||_||_||_||_||_|\n";

        assertEquals("000000000", new IngeniousDigitList(zeros).toString());


        String ones =
            "                           \n" +
            "  |  |  |  |  |  |  |  |  |\n" +
            "  |  |  |  |  |  |  |  |  |\n";

        assertEquals("111111111", new IngeniousDigitList(ones).toString());


        String twos =
            " _  _  _  _  _  _  _  _  _ \n" +
            " _| _| _| _| _| _| _| _| _|\n" +
            "|_ |_ |_ |_ |_ |_ |_ |_ |_ \n";

        assertEquals("222222222", new IngeniousDigitList(twos).toString());


        String threes =
            " _  _  _  _  _  _  _  _  _ \n" +
            " _| _| _| _| _| _| _| _| _|\n" +
            " _| _| _| _| _| _| _| _| _|\n";

        assertEquals("333333333", new IngeniousDigitList(threes).toString());


        String fours =
            "                           \n" +
            "|_||_||_||_||_||_||_||_||_|\n" +
            "  |  |  |  |  |  |  |  |  |\n";

        assertEquals("444444444", new IngeniousDigitList(fours).toString());


        String fives =
            " _  _  _  _  _  _  _  _  _ \n" +
            "|_ |_ |_ |_ |_ |_ |_ |_ |_ \n" +
            " _| _| _| _| _| _| _| _| _|\n";

        assertEquals("555555555", new IngeniousDigitList(fives).toString());


        String sixes =
            " _  _  _  _  _  _  _  _  _ \n" +
            "|_ |_ |_ |_ |_ |_ |_ |_ |_ \n" +
            "|_||_||_||_||_||_||_||_||_|\n";

        assertEquals("666666666", new IngeniousDigitList(sixes).toString());


        String sevens =
            " _  _  _  _  _  _  _  _  _ \n" +
            "  |  |  |  |  |  |  |  |  |\n" +
            "  |  |  |  |  |  |  |  |  |\n";

        assertEquals("777777777", new IngeniousDigitList(sevens).toString());


        String eights =
            " _  _  _  _  _  _  _  _  _ \n" +
            "|_||_||_||_||_||_||_||_||_|\n" +
            "|_||_||_||_||_||_||_||_||_|\n";

        assertEquals("888888888", new IngeniousDigitList(eights).toString());


        String nines =
            " _  _  _  _  _  _  _  _  _ \n" +
            "|_||_||_||_||_||_||_||_||_|\n" +
            " _| _| _| _| _| _| _| _| _|\n";

        assertEquals("999999999", new IngeniousDigitList(nines).toString());


        String count =
            "    _  _     _  _  _  _  _ \n" +
            "  | _| _||_||_ |_   ||_||_|\n" +
            "  ||_  _|  | _||_|  ||_| _|\n";

        assertEquals("123456789", new IngeniousDigitList(count).toString());
    }
}
