/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.arch;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class IngeniousNumberTest {
    @Test void ingeniousDigitsShouldResolveToThemselves() {
        for(int number = 0; number < 9; number++){
            IngeniousDigit digit = new IngeniousDigit(number);
            assertEquals(digit.toInt(), number, "Ingenious Digit " + number + " should parse to itself");
        }
    }

    @Test void invalidShouldBeQuestionDigits(){
        String invalidDigit =
            "   \n" +
            "| |\n" +
            "|_|\n";

        assertEquals("?", new IngeniousDigit(invalidDigit).toString());
    }
}
