/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.arch;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.List;

import org.junit.jupiter.api.Test;

class IngeniousFileUtilsTest {
    @Test void shouldParseStoryFile() throws FileNotFoundException, IOException, URISyntaxException {
        File ingeniousFile = new File(IngeniousFileUtils.class.getResource("/story1-numbers.txt").toURI());

        List<IngeniousDigitList> digitLists = IngeniousFileUtils.readIngeniousFile(ingeniousFile);
        assertEquals(11, digitLists.size(), "Should parse all the entires in a file");
    }
}
